export const Routes = {
  profile: "Profile",
  sequences: "Sequences",
  sequenceDetail: "SequenceDetail",
  feedDetail: "feedDetail",
  upload: "Upload",
  camera: "Camera",
  cameraSettings: "CameraSettings",
  generalSettings: "GeneralSettings",
  login: "Login",
  register: "Register",
  forgotPassword: "ForgotPassword",
  marketplace: "Marketplace",
  marketplaceDetail: "MarketplaceDetail",
  marketplaceReceived: "MarketplaceReceived",
  tabHome: "Home",
  walkthrough: "Walkthough",
  welcomeWalkthrough: "WelcomeWalkthrough",
  noInternetAccess: "NoInternetAccess",
  map: "map",
  nonUserTab: "NonUserTab",
  profileSequence: "ProfileSequence",
};
