export const Routes = {
  stackNavigator: 'StackNavigator',
  tabNavigator: 'TabNavigator',
  profileNavigator: 'ProfileNavigator',
  cameraNavigator: 'CameraNavigator',
  cameraTab: 'CameraTab',
  uploadTab: 'UploadTab',
  auth: 'Auth',
  profile: 'Profile',
  sequences: 'Sequences',
  sequenceDetail: 'SequenceDetail',
  feedDetail: 'feedDetail',
  upload: 'Upload',
  uploadCompleted: 'UploadCompleted',
  camera: 'Camera',
  cameraSettings: 'CameraSettings',
  generalSettings: 'GeneralSettings',
  login: 'Login',
  register: 'Register',
  forgotPassword: 'ForgotPassword',
  marketplace: 'Marketplace',
  marketplaceDetail: 'MarketplaceDetail',
  marketplaceReceived: 'MarketplaceReceived',
  marketplaceReady: 'MarketplaceReady',
  marketplaceSoon: 'MarketplaceSoon',
  tabHome: 'Home',
  captureWalkthrough: 'CaptureWalkthrough',
  welcomeWalkthrough: 'WelcomeWalkthrough',
  noInternetAccess: 'NoInternetAccess',
  map: 'Map',
  nonUserTab: 'NonUserTab',
  profileSequence: 'ProfileSequence',
  webview: 'WebviewScreen',
  profileSettings: 'ProfileSettings',
  profileEdit: 'profileEdit',
  leaders: 'Leaders',
  language: 'Language',
  howToScore: 'HowToScore',
  captureCompleted: 'CaptureCompleted',
  award: 'Award',
  deleteAccount: 'DeleteAccount',
  stackUserFeed: 'StackUserFeed',
  stackUserFeedDetail: 'StackUserFeedDetail',
} as const;

export type RouteName = (typeof Routes)[keyof typeof Routes];
