export const Routes = {
  profile: "Profile",
  sequences: "Sequences",
  sequenceDetail: "SequenceDetail",
  upload: "Upload",
  camera: "Camera",
  cameraSettings: "CameraSettings",
  generalSettings: "GeneralSettings",
  login: "Login",
  register: "Register",
  forgotPassword: "ForgotPassword",
  marketplace: "Marketplace",
  tabHome: "Home",
  walkthrough: "Walkthough",
  welcomeWalkthrough:"WelcomeWalkthrough",
};
