export const UPDATE_SELECTED_IMAGES = "UPDATE_SELECTED_IMAGES";
export const UPDATE_UPLOADED_IMAGES = "UPDATE_UPLOADED_IMAGES";
export const UPDATE_ALL_SELECT = "UPDATE_ALL_SELECT";
export const GET_TOKEN_START = "GET_TOKEN_START";
export const GET_TOKEN_SUCCESS = "GET_TOKEN_SUCCESS";
export const GET_TOKEN_ERROR = "GET_TOKEN_ERROR";
export const GET_USER_INFORMATION = "GET_USER_INFORMATION";
export const GET_USER_INDEX_TYPE = "GET_USER_INDEX_TYPE";
