export const UPDATE_SELECTED_IMAGES = "UPDATE_SELECTED_IMAGES";
export const UPDATE_UPLOADED_IMAGES = "UPDATE_UPLOADED_IMAGES";
export const UPDATE_ALL_SELECT = "UPDATE_ALL_SELECT";
export const UPDATE_GPS_ACCURACY = "UPDATE_GPS_ACCURACY";
export const UPDATE_GPS_STATUS = "UPDATE_GPS_STATUS";
export const UPDATE_CAMERA_STATUS = "UPDATE_CAMERA_STATUS";
export const UPDATE_CAMERA_REF = "UPDATE_CAMERA_REF";