export const UPDATE_SELECTED_IMAGES = "UPDATE_SELECTED_IMAGES";
export const UPDATE_UPLOADED_IMAGES = "UPDATE_UPLOADED_IMAGES";
export const UPDATE_ALL_SELECT = "UPDATE_ALL_SELECT";
export const GET_TOKEN_START = "GET_TOKEN_START";
