export const styles = {
  circles: {
    circleRadius: [
      "interpolate",
      ["linear"],
      ["zoom"],
      7.9,
      4,
      8,
      0,
      14,
      0,
      14.1,
      5,
    ],
    circleBlur: ["interpolate", ["linear"], ["zoom"], 14, 0, 22, 0.5],
    circleColor: "#146aff",
  },
  circlesOpacity: {
    circleColor: "#146aff",
    circleStrokeColor: "#146aff",
    circleStrokeOpacity: 0.4,
    circleStrokeWidth: [
      "interpolate",
      ["linear"],
      ["zoom"],
      7,
      1,
      7.1,
      0,
      14,
      0,
      14.1,
      2,
    ],
  },

  userLocation:{
    circleColor: "#1AD971",
    circleStrokeColor: "#1AD971",
    circleStrokeOpacity: 0.4,
    circleStrokeWidth: [
      "interpolate",
      ["linear"],
      ["zoom"],
      7,
      1,
      7.1,
      0,
      14,
      0,
      14.1,
      2,
    ],
    
  },
  lineStyles: {
    lineColor: "#146aff",
  },
};
